package de.upb.soot.jimple;

import de.upb.soot.jimple.expr.AddExpr;
import de.upb.soot.jimple.expr.AndExpr;
import de.upb.soot.jimple.expr.CastExpr;
import de.upb.soot.jimple.expr.CmpExpr;
import de.upb.soot.jimple.expr.CmpgExpr;
import de.upb.soot.jimple.expr.CmplExpr;
import de.upb.soot.jimple.expr.DivExpr;
import de.upb.soot.jimple.expr.DynamicInvokeExpr;
import de.upb.soot.jimple.expr.EqExpr;
import de.upb.soot.jimple.expr.GeExpr;
import de.upb.soot.jimple.expr.GtExpr;
import de.upb.soot.jimple.expr.InstanceOfExpr;
import de.upb.soot.jimple.expr.InterfaceInvokeExpr;
import de.upb.soot.jimple.expr.LeExpr;
import de.upb.soot.jimple.expr.LengthExpr;
import de.upb.soot.jimple.expr.LtExpr;
import de.upb.soot.jimple.expr.MulExpr;
import de.upb.soot.jimple.expr.NeExpr;
import de.upb.soot.jimple.expr.NegExpr;
import de.upb.soot.jimple.expr.NewArrayExpr;
import de.upb.soot.jimple.expr.NewExpr;
import de.upb.soot.jimple.expr.NewMultiArrayExpr;
import de.upb.soot.jimple.expr.OrExpr;
import de.upb.soot.jimple.expr.RemExpr;
import de.upb.soot.jimple.expr.ShlExpr;
import de.upb.soot.jimple.expr.ShrExpr;
import de.upb.soot.jimple.expr.SpecialInvokeExpr;
import de.upb.soot.jimple.expr.StaticInvokeExpr;
import de.upb.soot.jimple.expr.SubExpr;
import de.upb.soot.jimple.expr.UshrExpr;
import de.upb.soot.jimple.expr.VirtualInvokeExpr;
import de.upb.soot.jimple.expr.XorExpr;

public interface ExprSwitch extends IVisitor
{
    public abstract void caseAddExpr(AddExpr v);
    public abstract void caseAndExpr(AndExpr v);
    public abstract void caseCmpExpr(CmpExpr v);
    public abstract void caseCmpgExpr(CmpgExpr v);
    public abstract void caseCmplExpr(CmplExpr v);
    public abstract void caseDivExpr(DivExpr v);
    public abstract void caseEqExpr(EqExpr v);
    public abstract void caseNeExpr(NeExpr v);
    public abstract void caseGeExpr(GeExpr v);
    public abstract void caseGtExpr(GtExpr v);
    public abstract void caseLeExpr(LeExpr v);
    public abstract void caseLtExpr(LtExpr v);
    public abstract void caseMulExpr(MulExpr v);
    public abstract void caseOrExpr(OrExpr v);
    public abstract void caseRemExpr(RemExpr v);
    public abstract void caseShlExpr(ShlExpr v);
    public abstract void caseShrExpr(ShrExpr v);
    public abstract void caseUshrExpr(UshrExpr v);
    public abstract void caseSubExpr(SubExpr v);
    public abstract void caseXorExpr(XorExpr v);
    public abstract void caseInterfaceInvokeExpr(InterfaceInvokeExpr v);
    public abstract void caseSpecialInvokeExpr(SpecialInvokeExpr v);
    public abstract void caseStaticInvokeExpr(StaticInvokeExpr v);
    public abstract void caseVirtualInvokeExpr(VirtualInvokeExpr v);
    public abstract void caseDynamicInvokeExpr(DynamicInvokeExpr v);
    public abstract void caseCastExpr(CastExpr v);
    public abstract void caseInstanceOfExpr(InstanceOfExpr v);
    public abstract void caseNewArrayExpr(NewArrayExpr v);
    public abstract void caseNewMultiArrayExpr(NewMultiArrayExpr v);
    public abstract void caseNewExpr(NewExpr v);
    public abstract void caseLengthExpr(LengthExpr v);
    public abstract void caseNegExpr(NegExpr v);
    public abstract void defaultCase(Object obj);
}
