/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * gradle plugin from the resource data it found. It
 * should not be modified by hand.
 */
package com.google.android.gms.panorama;

public final class R {
    public static final class attr {
        public static final int adSize = 0x7f020022;
        public static final int adSizes = 0x7f020023;
        public static final int adUnitId = 0x7f020024;
        public static final int appTheme = 0x7f020025;
        public static final int buyButtonAppearance = 0x7f02002e;
        public static final int buyButtonHeight = 0x7f02002f;
        public static final int buyButtonText = 0x7f020030;
        public static final int buyButtonWidth = 0x7f020031;
        public static final int cameraBearing = 0x7f020032;
        public static final int cameraTargetLat = 0x7f020033;
        public static final int cameraTargetLng = 0x7f020034;
        public static final int cameraTilt = 0x7f020035;
        public static final int cameraZoom = 0x7f020036;
        public static final int circleCrop = 0x7f020038;
        public static final int environment = 0x7f02005d;
        public static final int fragmentMode = 0x7f020060;
        public static final int fragmentStyle = 0x7f020061;
        public static final int imageAspectRatio = 0x7f02006a;
        public static final int imageAspectRatioAdjust = 0x7f02006b;
        public static final int liteMode = 0x7f0200aa;
        public static final int mapType = 0x7f0200ac;
        public static final int maskedWalletDetailsBackground = 0x7f0200ad;
        public static final int maskedWalletDetailsButtonBackground = 0x7f0200ae;
        public static final int maskedWalletDetailsButtonTextAppearance = 0x7f0200af;
        public static final int maskedWalletDetailsHeaderTextAppearance = 0x7f0200b0;
        public static final int maskedWalletDetailsLogoImageType = 0x7f0200b1;
        public static final int maskedWalletDetailsLogoTextColor = 0x7f0200b2;
        public static final int maskedWalletDetailsTextAppearance = 0x7f0200b3;
        public static final int uiCompass = 0x7f0200fe;
        public static final int uiMapToolbar = 0x7f0200ff;
        public static final int uiRotateGestures = 0x7f020100;
        public static final int uiScrollGestures = 0x7f020101;
        public static final int uiTiltGestures = 0x7f020102;
        public static final int uiZoomControls = 0x7f020103;
        public static final int uiZoomGestures = 0x7f020104;
        public static final int useViewLifecycle = 0x7f020105;
        public static final int windowTransitionStyle = 0x7f02010e;
        public static final int zOrderOnTop = 0x7f02010f;
    }
    public static final class color {
        public static final int common_action_bar_splitter = 0x7f040025;
        public static final int common_signin_btn_dark_text_default = 0x7f040026;
        public static final int common_signin_btn_dark_text_disabled = 0x7f040027;
        public static final int common_signin_btn_dark_text_focused = 0x7f040028;
        public static final int common_signin_btn_dark_text_pressed = 0x7f040029;
        public static final int common_signin_btn_default_background = 0x7f04002a;
        public static final int common_signin_btn_light_text_default = 0x7f04002b;
        public static final int common_signin_btn_light_text_disabled = 0x7f04002c;
        public static final int common_signin_btn_light_text_focused = 0x7f04002d;
        public static final int common_signin_btn_light_text_pressed = 0x7f04002e;
        public static final int common_signin_btn_text_dark = 0x7f04002f;
        public static final int common_signin_btn_text_light = 0x7f040030;
        public static final int wallet_bright_foreground_disabled_holo_light = 0x7f04005a;
        public static final int wallet_bright_foreground_holo_dark = 0x7f04005b;
        public static final int wallet_bright_foreground_holo_light = 0x7f04005c;
        public static final int wallet_dim_foreground_disabled_holo_dark = 0x7f04005d;
        public static final int wallet_dim_foreground_holo_dark = 0x7f04005e;
        public static final int wallet_dim_foreground_inverse_disabled_holo_dark = 0x7f04005f;
        public static final int wallet_dim_foreground_inverse_holo_dark = 0x7f040060;
        public static final int wallet_highlighted_text_holo_dark = 0x7f040061;
        public static final int wallet_highlighted_text_holo_light = 0x7f040062;
        public static final int wallet_hint_foreground_holo_dark = 0x7f040063;
        public static final int wallet_hint_foreground_holo_light = 0x7f040064;
        public static final int wallet_holo_blue_light = 0x7f040065;
        public static final int wallet_link_text_light = 0x7f040066;
        public static final int wallet_primary_text_holo_light = 0x7f040067;
        public static final int wallet_secondary_text_holo_dark = 0x7f040068;
    }
    public static final class drawable {
        public static final int cast_ic_notification_0 = 0x7f06003a;
        public static final int cast_ic_notification_1 = 0x7f06003b;
        public static final int cast_ic_notification_2 = 0x7f06003c;
        public static final int cast_ic_notification_connecting = 0x7f06003d;
        public static final int cast_ic_notification_on = 0x7f06003e;
        public static final int common_full_open_on_phone = 0x7f060041;
        public static final int common_ic_googleplayservices = 0x7f060042;
        public static final int common_signin_btn_icon_dark = 0x7f060043;
        public static final int common_signin_btn_icon_disabled_dark = 0x7f060044;
        public static final int common_signin_btn_icon_disabled_focus_dark = 0x7f060045;
        public static final int common_signin_btn_icon_disabled_focus_light = 0x7f060046;
        public static final int common_signin_btn_icon_disabled_light = 0x7f060047;
        public static final int common_signin_btn_icon_focus_dark = 0x7f060048;
        public static final int common_signin_btn_icon_focus_light = 0x7f060049;
        public static final int common_signin_btn_icon_light = 0x7f06004a;
        public static final int common_signin_btn_icon_normal_dark = 0x7f06004b;
        public static final int common_signin_btn_icon_normal_light = 0x7f06004c;
        public static final int common_signin_btn_icon_pressed_dark = 0x7f06004d;
        public static final int common_signin_btn_icon_pressed_light = 0x7f06004e;
        public static final int common_signin_btn_text_dark = 0x7f06004f;
        public static final int common_signin_btn_text_disabled_dark = 0x7f060050;
        public static final int common_signin_btn_text_disabled_focus_dark = 0x7f060051;
        public static final int common_signin_btn_text_disabled_focus_light = 0x7f060052;
        public static final int common_signin_btn_text_disabled_light = 0x7f060053;
        public static final int common_signin_btn_text_focus_dark = 0x7f060054;
        public static final int common_signin_btn_text_focus_light = 0x7f060055;
        public static final int common_signin_btn_text_light = 0x7f060056;
        public static final int common_signin_btn_text_normal_dark = 0x7f060057;
        public static final int common_signin_btn_text_normal_light = 0x7f060058;
        public static final int common_signin_btn_text_pressed_dark = 0x7f060059;
        public static final int common_signin_btn_text_pressed_light = 0x7f06005a;
        public static final int ic_plusone_medium_off_client = 0x7f060070;
        public static final int ic_plusone_small_off_client = 0x7f060071;
        public static final int ic_plusone_standard_off_client = 0x7f060072;
        public static final int ic_plusone_tall_off_client = 0x7f060073;
        public static final int powered_by_google_dark = 0x7f060096;
        public static final int powered_by_google_light = 0x7f060097;
    }
    public static final class id {
        public static final int adjust_height = 0x7f070010;
        public static final int adjust_width = 0x7f070011;
        public static final int book_now = 0x7f070016;
        public static final int buyButton = 0x7f07001d;
        public static final int buy_now = 0x7f07001e;
        public static final int buy_with_google = 0x7f07001f;
        public static final int cast_notification_id = 0x7f070020;
        public static final int classic = 0x7f070023;
        public static final int donate_with_google = 0x7f07002d;
        public static final int grayscale = 0x7f07003e;
        public static final int holo_dark = 0x7f070041;
        public static final int holo_light = 0x7f070042;
        public static final int hybrid = 0x7f070045;
        public static final int match_parent = 0x7f070053;
        public static final int monochrome = 0x7f070057;
        public static final int none = 0x7f07005a;
        public static final int normal = 0x7f07005b;
        public static final int production = 0x7f070061;
        public static final int sandbox = 0x7f070069;
        public static final int satellite = 0x7f07006a;
        public static final int selectionDetails = 0x7f070075;
        public static final int slide = 0x7f07007c;
        public static final int strict_sandbox = 0x7f070083;
        public static final int terrain = 0x7f070088;
        public static final int test = 0x7f070089;
        public static final int wrap_content = 0x7f0700a0;
    }
    public static final class integer {
        public static final int google_play_services_version = 0x7f080003;
    }
    public static final class raw {
        public static final int gtm_analytics = 0x7f0c0000;
    }
    public static final class string {
        public static final int accept = 0x7f0d0010;
        public static final int auth_google_play_services_client_facebook_display_name = 0x7f0d0016;
        public static final int auth_google_play_services_client_google_display_name = 0x7f0d0017;
        public static final int cast_notification_connected_message = 0x7f0d0018;
        public static final int cast_notification_connecting_message = 0x7f0d0019;
        public static final int cast_notification_disconnect = 0x7f0d001a;
        public static final int common_android_wear_notification_needs_update_text = 0x7f0d001b;
        public static final int common_android_wear_update_text = 0x7f0d001c;
        public static final int common_android_wear_update_title = 0x7f0d001d;
        public static final int common_google_play_services_api_unavailable_text = 0x7f0d001e;
        public static final int common_google_play_services_enable_button = 0x7f0d001f;
        public static final int common_google_play_services_enable_text = 0x7f0d0020;
        public static final int common_google_play_services_enable_title = 0x7f0d0021;
        public static final int common_google_play_services_error_notification_requested_by_msg = 0x7f0d0022;
        public static final int common_google_play_services_install_button = 0x7f0d0023;
        public static final int common_google_play_services_install_text_phone = 0x7f0d0024;
        public static final int common_google_play_services_install_text_tablet = 0x7f0d0025;
        public static final int common_google_play_services_install_title = 0x7f0d0026;
        public static final int common_google_play_services_invalid_account_text = 0x7f0d0027;
        public static final int common_google_play_services_invalid_account_title = 0x7f0d0028;
        public static final int common_google_play_services_needs_enabling_title = 0x7f0d0029;
        public static final int common_google_play_services_network_error_text = 0x7f0d002a;
        public static final int common_google_play_services_network_error_title = 0x7f0d002b;
        public static final int common_google_play_services_notification_needs_update_title = 0x7f0d002c;
        public static final int common_google_play_services_notification_ticker = 0x7f0d002d;
        public static final int common_google_play_services_sign_in_failed_text = 0x7f0d002e;
        public static final int common_google_play_services_sign_in_failed_title = 0x7f0d002f;
        public static final int common_google_play_services_unknown_issue = 0x7f0d0030;
        public static final int common_google_play_services_unsupported_text = 0x7f0d0031;
        public static final int common_google_play_services_unsupported_title = 0x7f0d0032;
        public static final int common_google_play_services_update_button = 0x7f0d0033;
        public static final int common_google_play_services_update_text = 0x7f0d0034;
        public static final int common_google_play_services_update_title = 0x7f0d0035;
        public static final int common_google_play_services_updating_text = 0x7f0d0036;
        public static final int common_google_play_services_updating_title = 0x7f0d0037;
        public static final int common_open_on_phone = 0x7f0d0038;
        public static final int common_signin_button_text = 0x7f0d0039;
        public static final int common_signin_button_text_long = 0x7f0d003a;
        public static final int create_calendar_message = 0x7f0d003b;
        public static final int create_calendar_title = 0x7f0d003c;
        public static final int decline = 0x7f0d003d;
        public static final int store_picture_message = 0x7f0d0079;
        public static final int store_picture_title = 0x7f0d007a;
        public static final int wallet_buy_button_place_holder = 0x7f0d0089;
    }
    public static final class style {
        public static final int Theme_IAPTheme = 0x7f0e00bd;
        public static final int WalletFragmentDefaultButtonTextAppearance = 0x7f0e00c5;
        public static final int WalletFragmentDefaultDetailsHeaderTextAppearance = 0x7f0e00c6;
        public static final int WalletFragmentDefaultDetailsTextAppearance = 0x7f0e00c7;
        public static final int WalletFragmentDefaultStyle = 0x7f0e00c8;
    }
    public static final class styleable {
        public static final int[] AdsAttrs = { 0x7f020022, 0x7f020023, 0x7f020024 };
        public static final int AdsAttrs_adSize = 0;
        public static final int AdsAttrs_adSizes = 1;
        public static final int AdsAttrs_adUnitId = 2;
        public static final int[] CustomWalletTheme = { 0x7f02010e };
        public static final int CustomWalletTheme_windowTransitionStyle = 0;
        public static final int[] LoadingImageView = { 0x7f020038, 0x7f02006a, 0x7f02006b };
        public static final int LoadingImageView_circleCrop = 0;
        public static final int LoadingImageView_imageAspectRatio = 1;
        public static final int LoadingImageView_imageAspectRatioAdjust = 2;
        public static final int[] MapAttrs = { 0x7f020032, 0x7f020033, 0x7f020034, 0x7f020035, 0x7f020036, 0x7f0200aa, 0x7f0200ac, 0x7f0200fe, 0x7f0200ff, 0x7f020100, 0x7f020101, 0x7f020102, 0x7f020103, 0x7f020104, 0x7f020105, 0x7f02010f };
        public static final int MapAttrs_cameraBearing = 0;
        public static final int MapAttrs_cameraTargetLat = 1;
        public static final int MapAttrs_cameraTargetLng = 2;
        public static final int MapAttrs_cameraTilt = 3;
        public static final int MapAttrs_cameraZoom = 4;
        public static final int MapAttrs_liteMode = 5;
        public static final int MapAttrs_mapType = 6;
        public static final int MapAttrs_uiCompass = 7;
        public static final int MapAttrs_uiMapToolbar = 8;
        public static final int MapAttrs_uiRotateGestures = 9;
        public static final int MapAttrs_uiScrollGestures = 10;
        public static final int MapAttrs_uiTiltGestures = 11;
        public static final int MapAttrs_uiZoomControls = 12;
        public static final int MapAttrs_uiZoomGestures = 13;
        public static final int MapAttrs_useViewLifecycle = 14;
        public static final int MapAttrs_zOrderOnTop = 15;
        public static final int[] WalletFragmentOptions = { 0x7f020025, 0x7f02005d, 0x7f020060, 0x7f020061 };
        public static final int WalletFragmentOptions_appTheme = 0;
        public static final int WalletFragmentOptions_environment = 1;
        public static final int WalletFragmentOptions_fragmentMode = 2;
        public static final int WalletFragmentOptions_fragmentStyle = 3;
        public static final int[] WalletFragmentStyle = { 0x7f02002e, 0x7f02002f, 0x7f020030, 0x7f020031, 0x7f0200ad, 0x7f0200ae, 0x7f0200af, 0x7f0200b0, 0x7f0200b1, 0x7f0200b2, 0x7f0200b3 };
        public static final int WalletFragmentStyle_buyButtonAppearance = 0;
        public static final int WalletFragmentStyle_buyButtonHeight = 1;
        public static final int WalletFragmentStyle_buyButtonText = 2;
        public static final int WalletFragmentStyle_buyButtonWidth = 3;
        public static final int WalletFragmentStyle_maskedWalletDetailsBackground = 4;
        public static final int WalletFragmentStyle_maskedWalletDetailsButtonBackground = 5;
        public static final int WalletFragmentStyle_maskedWalletDetailsButtonTextAppearance = 6;
        public static final int WalletFragmentStyle_maskedWalletDetailsHeaderTextAppearance = 7;
        public static final int WalletFragmentStyle_maskedWalletDetailsLogoImageType = 8;
        public static final int WalletFragmentStyle_maskedWalletDetailsLogoTextColor = 9;
        public static final int WalletFragmentStyle_maskedWalletDetailsTextAppearance = 10;
    }
}
