package sootup.spark;

/*-
 * #%L
 * SootUp
 * %%
 * Copyright (C) 2002-2026 Ondrej Lhotak, Kadiray Karakaya and others
 * %%
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as
 * published by the Free Software Foundation, either version 2.1 of the
 * License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Lesser Public License for more details.
 *
 * You should have received a copy of the GNU General Lesser Public
 * License along with this program.  If not, see
 * <http://www.gnu.org/licenses/lgpl-2.1.html>.
 * #L%
 */

import java.util.ArrayDeque;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Deque;
import java.util.HashMap;
import java.util.HashSet;
import java.util.LinkedHashSet;
import java.util.Map;
import java.util.Objects;
import java.util.Set;
import lombok.NonNull;
import org.graph4j.Digraph;
import org.graph4j.PredecessorIterator;
import org.graph4j.SuccessorIterator;
import sootup.core.signatures.FieldSignature;
import sootup.spark.node.AllocationNode;
import sootup.spark.node.InstanceFieldRefNode;
import sootup.spark.node.Node;

/**
 * Worklist-based incremental Andersen-style points-to propagation.
 *
 * <p>Used by the on-the-fly call graph builder, which needs intermediate points-to results to
 * resolve virtual call sites. Edges are fed in via {@link #addEdge(Node, Node)} as the PAG grows;
 * {@link #propagate()} drains the dirty-node and dirty-heap worklists to bring points-to and heap
 * state to a fixed point with respect to the currently-known edges. The analysis can then be
 * re-driven when more edges are discovered, without recomputing from scratch.
 */
public class IncrementalPointsToAnalysis {

  private final PAG pag;
  private final Map<Node, Set<AllocationNode>> pointsTo = new HashMap<>();
  private final Map<HeapKey, Set<AllocationNode>> heap = new HashMap<>();
  private final Map<Node, Set<InstanceFieldRefNode>> baseToIFRs = new HashMap<>();
  private final Deque<Node> dirty = new ArrayDeque<>();
  private final Set<Node> dirtySet = new HashSet<>();
  private final Deque<HeapKey> dirtyHeap = new ArrayDeque<>();
  private final Set<HeapKey> dirtyHeapSet = new HashSet<>();

  public IncrementalPointsToAnalysis(@NonNull PAG pag) {
    this.pag = pag;
  }

  public PAG getPag() {
    return pag;
  }

  /**
   * Adds an edge to the underlying PAG and applies its semantic effect to the points-to / heap
   * state. New work generated by the edge is enqueued for {@link #propagate()} to drain.
   */
  public void addEdge(@NonNull Node src, @NonNull Node tgt) {
    pag.addEdge(src, tgt);
    Digraph<Node, PAGEdge> d = pag.getDelegate();
    int sIdx = d.findVertex(src);
    int tIdx = d.findVertex(tgt);
    if (sIdx < 0 || tIdx < 0 || !d.containsEdge(sIdx, tIdx)) return;
    PAGEdge edge = d.getEdgeLabel(sIdx, tIdx);
    indexIFR(src);
    indexIFR(tgt);
    apply(src, tgt, edge.getEdgeType());
  }

  /** Drains worklists; bringing points-to and heap state up to date with currently-known edges. */
  public void propagate() {
    Digraph<Node, PAGEdge> graph = pag.getDelegate();
    while (!dirty.isEmpty() || !dirtyHeap.isEmpty()) {
      while (!dirty.isEmpty()) {
        Node n = dirty.poll();
        dirtySet.remove(n);
        int nIdx = graph.findVertex(n);
        if (nIdx < 0) continue;
        Set<AllocationNode> nPts = ptsOf(n);

        SuccessorIterator<PAGEdge> succIt = graph.successorIterator(nIdx);
        while (succIt.hasNext()) {
          int tgtIdx = succIt.next();
          PAGEdge e = succIt.getEdgeLabel();
          Node tgt = graph.getVertexLabel(tgtIdx);
          switch (e.getEdgeType()) {
            case ASSIGNMENT -> {
              if (unionInto(pointsTo, tgt, nPts)) enqueue(tgt);
            }
            case STORE -> {
              if (tgt instanceof InstanceFieldRefNode ifr) {
                for (AllocationNode o : ptsOf(ifr.getBase())) {
                  if (unionIntoHeap(o, ifr.getField(), nPts)) enqueueHeap(o, ifr.getField());
                }
              }
            }
            default -> {}
          }
        }

        // pts(n) growth affects every IFR whose base is n: re-apply its stores and loads.
        Set<InstanceFieldRefNode> ifrs = baseToIFRs.get(n);
        if (ifrs != null) {
          for (InstanceFieldRefNode ifr : ifrs) {
            int ifrIdx = graph.findVertex(ifr);
            if (ifrIdx < 0) continue;
            PredecessorIterator<PAGEdge> predIt = graph.predecessorIterator(ifrIdx);
            while (predIt.hasNext()) {
              int srcIdx = predIt.next();
              PAGEdge se = predIt.getEdgeLabel();
              if (se.getEdgeType() == PAGEdge.EdgeType.STORE) {
                applyStore(graph.getVertexLabel(srcIdx), ifr);
              }
            }
            SuccessorIterator<PAGEdge> outIt = graph.successorIterator(ifrIdx);
            while (outIt.hasNext()) {
              int tgtIdx = outIt.next();
              PAGEdge le = outIt.getEdgeLabel();
              if (le.getEdgeType() == PAGEdge.EdgeType.LOAD) {
                applyLoad(ifr, graph.getVertexLabel(tgtIdx));
              }
            }
          }
        }
      }

      while (!dirtyHeap.isEmpty()) {
        HeapKey hk = dirtyHeap.poll();
        dirtyHeapSet.remove(hk);
        Set<AllocationNode> stored = heap.get(hk);
        if (stored == null) continue;
        for (Map.Entry<Node, Set<InstanceFieldRefNode>> entry : baseToIFRs.entrySet()) {
          if (!ptsOf(entry.getKey()).contains(hk.obj())) continue;
          for (InstanceFieldRefNode ifr : entry.getValue()) {
            if (!ifr.getField().equals(hk.field())) continue;
            int ifrIdx = graph.findVertex(ifr);
            if (ifrIdx < 0) continue;
            SuccessorIterator<PAGEdge> outIt = graph.successorIterator(ifrIdx);
            while (outIt.hasNext()) {
              int tgtIdx = outIt.next();
              PAGEdge le = outIt.getEdgeLabel();
              if (le.getEdgeType() == PAGEdge.EdgeType.LOAD) {
                Node tgt = graph.getVertexLabel(tgtIdx);
                if (unionInto(pointsTo, tgt, stored)) enqueue(tgt);
              }
            }
          }
        }
      }
    }
  }

  public Set<AllocationNode> reachingObjects(@NonNull Node n) {
    // Return a real copy, not a view over the live map-backed set: callers (e.g. the on-the-fly
    // call graph builder) iterate the result while resolving virtual calls, and that resolution
    // can trigger further edge propagation that grows pts(n) mid-iteration.
    return Collections.unmodifiableSet(new LinkedHashSet<>(ptsOf(n)));
  }

  public Map<Node, Set<AllocationNode>> getPointsTo() {
    return Collections.unmodifiableMap(pointsTo);
  }

  public Map<HeapKey, Set<AllocationNode>> getHeap() {
    return Collections.unmodifiableMap(heap);
  }

  private void apply(Node src, Node tgt, PAGEdge.EdgeType type) {
    switch (type) {
      case ALLOCATION -> {
        if (src instanceof AllocationNode a && addPts(tgt, a)) enqueue(tgt);
      }
      case ASSIGNMENT -> {
        if (unionInto(pointsTo, tgt, ptsOf(src))) enqueue(tgt);
      }
      case STORE -> {
        if (tgt instanceof InstanceFieldRefNode ifr) applyStore(src, ifr);
      }
      case LOAD -> {
        if (src instanceof InstanceFieldRefNode ifr) applyLoad(ifr, tgt);
      }
    }
  }

  private void applyStore(Node src, InstanceFieldRefNode ifr) {
    Set<AllocationNode> srcPts = ptsOf(src);
    if (srcPts.isEmpty()) return;
    for (AllocationNode o : ptsOf(ifr.getBase())) {
      if (unionIntoHeap(o, ifr.getField(), srcPts)) enqueueHeap(o, ifr.getField());
    }
  }

  private void applyLoad(InstanceFieldRefNode ifr, Node tgt) {
    // Snapshot: pts(ifr.getBase()) and pts(tgt) can be the same live set (e.g. "x = x.f"),
    // and unionInto below grows pts(tgt), so iterating the map-backed set directly would
    // throw ConcurrentModificationException.
    for (AllocationNode o : new ArrayList<>(ptsOf(ifr.getBase()))) {
      Set<AllocationNode> stored = heap.get(new HeapKey(o, ifr.getField()));
      if (stored != null && unionInto(pointsTo, tgt, stored)) enqueue(tgt);
    }
  }

  private void indexIFR(Node n) {
    if (n instanceof InstanceFieldRefNode ifr) {
      baseToIFRs.computeIfAbsent(ifr.getBase(), k -> new LinkedHashSet<>()).add(ifr);
    }
  }

  private void enqueue(Node n) {
    if (dirtySet.add(n)) dirty.add(n);
  }

  private void enqueueHeap(AllocationNode o, FieldSignature f) {
    HeapKey hk = new HeapKey(o, f);
    if (dirtyHeapSet.add(hk)) dirtyHeap.add(hk);
  }

  private Set<AllocationNode> ptsOf(Node n) {
    Set<AllocationNode> s = pointsTo.get(n);
    return s == null ? Collections.emptySet() : s;
  }

  private boolean addPts(Node n, AllocationNode a) {
    return pointsTo.computeIfAbsent(n, k -> new LinkedHashSet<>()).add(a);
  }

  private static boolean unionInto(
      Map<Node, Set<AllocationNode>> map, Node n, Set<AllocationNode> incoming) {
    if (incoming.isEmpty()) return false;
    return map.computeIfAbsent(n, k -> new LinkedHashSet<>()).addAll(incoming);
  }

  private boolean unionIntoHeap(
      AllocationNode obj, FieldSignature f, Set<AllocationNode> incoming) {
    if (incoming.isEmpty()) return false;
    return heap.computeIfAbsent(new HeapKey(obj, f), k -> new LinkedHashSet<>()).addAll(incoming);
  }

  public record HeapKey(AllocationNode obj, FieldSignature field) {
    public HeapKey {
      Objects.requireNonNull(obj);
      Objects.requireNonNull(field);
    }
  }
}
