/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * gradle plugin from the resource data it found. It
 * should not be modified by hand.
 */
package com.marcohc.toasteroid;

public final class R {
    public static final class color {
        public static final int toasteroid_deleted = 0x7f040055;
        public static final int toasteroid_error = 0x7f040056;
        public static final int toasteroid_info = 0x7f040057;
        public static final int toasteroid_success = 0x7f040058;
        public static final int toasteroid_warning = 0x7f040059;
    }
    public static final class dimen {
        public static final int padding = 0x7f050033;
        public static final int small_padding = 0x7f050034;
        public static final int toasteroid_alpha_background = 0x7f050035;
        public static final int toasteroid_image_size = 0x7f050036;
    }
    public static final class drawable {
        public static final int ic_toasteroid_delete = 0x7f060076;
        public static final int ic_toasteroid_error = 0x7f060077;
        public static final int ic_toasteroid_info = 0x7f060078;
        public static final int ic_toasteroid_success = 0x7f060079;
        public static final int ic_toasteroid_warning = 0x7f06007a;
        public static final int toasteroid_rounded_shape = 0x7f06009a;
    }
    public static final class id {
        public static final int image = 0x7f070048;
        public static final int toastContainer = 0x7f070094;
        public static final int toastImage = 0x7f070095;
        public static final int toastMessage = 0x7f070096;
    }
    public static final class layout {
        public static final int toasteroid_layout = 0x7f090026;
    }
    public static final class style {
        public static final int toasteroid_font_size = 0x7f0e0103;
    }
}
