# enables auto-merge "merge when ready" feature in merge-queue driven workflows for dependabot PRs
name: Dependabotification handler

on:
  pull_request_target:
    paths: ["**/pom.xml"]

permissions:
  contents: write
  pull-requests: write

jobs:
  enable-auto-merge:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'
    steps:
      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v2
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"

      # Note: If you use status checks to test pull requests, you should enable Require status checks to pass before merging for the target branch for Dependabot pull requests. This branch protection rule ensures that pull requests are not merged unless all the required status checks pass. For more information, see "Managing a branch protection rule."
      - name: Enable auto-merge for Dependabot PRs
        # if: steps.metadata.outputs.update-type == 'version-update:semver-patch' && contains(steps.metadata.outputs.dependency-names, 'my-dependency')
        run: gh pr merge --auto --merge "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GH_TOKEN: ${{secrets.GITHUB_TOKEN}}

  auto-approve:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]' && secrets.SSE_BOT_PAT != ''
    steps:
      - name: Auto-approve Dependabot PRs
        uses: secure-software-engineering/actions/.github/workflows/auto-approve-dependabot.yml@roshansamantaray-patch-1
        with:
          token: ${{ secrets.SSE_BOT_PAT }}