name: Handle Dependabot PRs

on:
  pull_request:
    types: [opened, reopened, synchronize]

permissions:
  contents: write
  pull-requests: write

jobs:
  ApproveAndMerge:
    name: Auto approve Dependabot PRs
    runs-on: ubuntu-latest
    # Only run for PRs created by Dependabot - extended verification is done in the reusable workflow
    if: github.actor == 'dependabot[bot]'
    # These permissions are needed to approve pull requests
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@f4a75cfd619ee5ce8d5b864b0d183aff3c69b55a # v2.13.1
        with:
          egress-policy: audit

      - name: Auto approve Dependabot PR
        uses: secure-software-engineering/actions/dependabot@36a91c5b539e3e2e6eeb66ecdb01218abdd92e34 # develop
        with:
          token: ${{ secrets.AUTO_MERGE_PAT }}