name: PR Documentation Preview

permissions:
  pages: write
  deployments: write
  contents: write
  pull-requests: write

on:
  pull_request:
    types: [opened, synchronize, reopened, closed]
    paths:
      - 'mkdocs.yml'
      - 'sootup.examples/**'
      - 'docs/**'
      - '.github/workflows/deploy-pr-preview.yml'

concurrency: pages

jobs:
  deploy-preview:
    uses: secure-software-engineering/actions/pages/pr-review-action.yml@develop
    with:
      enable_comment: true
      title_prefix: "SootUp PR Preview: "