name: Deploy SNAPSHOT versions

on:
  push:
    branches:
      - develop

permissions:
  contents: read

jobs:
  deploy-snapshot:
    runs-on: ubuntu-latest
    name: Deploy SNAPSHOT version
    environment: deployment
    steps:
      - name: Checkout source code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Set up Java 17
        uses: actions/setup-java@03ad4de0992f5dab5e18fcb136590ce7c4a0ac95 # v5.6.0
        with:
          distribution: adopt
          java-package: jdk
          java-version: 17

      - name: Get project version
        run: |
          echo "PROJECT_VERSION=$(mvn help:evaluate -Dexpression=project.version -DforceStdout 2>/dev/null | grep -v '^\[' | tail -1)" >> $GITHUB_ENV

      - name: Deploy SNAPSHOT version
        if: endsWith(env.PROJECT_VERSION, '-SNAPSHOT')
        uses: secure-software-engineering/actions/deployment/maven-deployment@0caaeef2e50a42448e00423a073c676aebead49f # develop
        with:
          java-distribution: adopt
          java-version: 17
          server-id: central
          server-username: ${{ secrets.MAVEN_USERNAME }}
          server-password: ${{ secrets.MAVEN_CENTRAL_TOKEN }}
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          gpg-passphrase: ${{ secrets.GPG_PRIVATE_KEY_PASSPHRASE }}
          mvn-cli-args: '-DskipTests -Drelease'
          deploy-mode: snapshot
