name: Deploy to Maven Central
run-name: Deploy run ${{ github.run_number }} # Enumerates entries in the "workflow runs" view

on:
  push:
    branches:
      - develop
      - master

env:
  LATEST_BRANCH_NAME: develop
  SNAPSHOT_BRANCH_NAME: snapshot_version

jobs:
  deployment:
    name: Deployment
    runs-on: ubuntu-latest
    environment: deployment
    steps:
      - name: Checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      - name: Setup Java
        uses: actions/setup-java@f2beeb24e141e01a676f977032f5a29d81c9e27e # v5.1.0
        with:
          distribution: adopt
          java-package: jdk
          java-version: 17
          server-id: central                              # must match the serverId configured for the nexus-staging-maven-plugin
          server-username: MAVEN_USERNAME                 # Env var that holds the central publisher user name
          server-password: MAVEN_CENTRAL_TOKEN            # Env var that holds the central publisher user token
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }} # Substituted with the value stored in the referenced secret
          gpg-passphrase: MAVEN_GPG_PASSPHRASE            # Env var that holds the key's passphrase

      - name: SNAPSHOT version integrity check on latest branch   # enforce earlier? e.g. in the PR
        if: ${{ github.ref_name == env.LATEST_BRANCH_NAME }}
        run: |
          mvn org.apache.maven.plugins:maven-help-plugin:evaluate -Dexpression=project.version | grep -q -- '-SNAPSHOT$'

      - name: Ensure the proposed new version is higher than the latest   # enforce earlier? e.g. in the PR
        run: |
          echo "PROPOSED_NEW_VERSION=$(mvn org.apache.maven.plugins:maven-help-plugin:evaluate -Dexpression=project.version)" >> $GITHUB_ENV
          TMP_POM=$(mktemp)
          curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
                -H "Accept: application/vnd.github.v3.raw" \
                -O \
                https://api.github.com/repos/${{ github.repository }}/contents/pom.xml?ref=${{ github.ref_name }}
                -o "$TMP_POM"
          LATEST_VERSION=$(mvn -f "$TMP_POM" org.apache.maven.plugins:maven-help-plugin:2.1.1:evaluate -Dexpression=project.version)
          rm "$TMP_POM"
          
          # did the version not change?      
          if [ "$LATEST_VERSION" == "${{ env.PROPOSED_NEW_VERSION }}" ]; then
            if [ "${{ github.ref_name }}" == "${{ env.LATEST_BRANCH_NAME }}" ]; then
              exit 0
            else
              exit 1
            fi
          fi
          
          # is the new version higher? hint: does not handle 0.1.3-alpha versions.. just numbers! 
          if [ "$(printf "%s\n%s" "${{ env.PROPOSED_NEW_VERSION }}" "$LATEST_VERSION" | sort -V | head -n1)" = "${{ env.PROPOSED_NEW_VERSION }}" ]; then
              echo "Proposed new version is lower than the latest version!"
              echo "${{ env.PROPOSED_NEW_VERSION }} <= $LATEST_VERSION"
              exit 1
          fi

      - name: Deploy on Maven Central
        run: |
          # -U force updates just to make sure we are using latest dependencies
          # -B Batch mode (do not ask for user input), just in case
          # -D activate a profile via the release property (and disable defined submodules that should not be deployed)
          mvn -U -B -ntp clean deploy -Drelease -DskipTests
        env:
          MAVEN_USERNAME: ${{ secrets.SONATYPE_USER }}
          MAVEN_CENTRAL_TOKEN: ${{ secrets.SONATYPE_PW }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.GPG_PRIVATE_KEY_PASSPHRASE }}

      - name: Tag new version
        if: ${{ github.ref_name == 'master' }}
        run: |
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git config --global user.name "${{ github.actor }}"
          git tag -a ${{ env.PROPOSED_NEW_VERSION }} -m "version ${{ env.PROPOSED_NEW_VERSION }}"
          git push origin ${{ env.PROPOSED_NEW_VERSION }}

      - name: Create GitHub release
        if: ${{ github.ref_name == 'master' }}
        run: |
          gh release create ${{ env.PROPOSED_NEW_VERSION }} --title ${{ env.PROPOSED_NEW_VERSION }} --generate-notes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  increase-snapshot-version:
    if: ${{ github.ref_name == 'master' }}
    runs-on: ubuntu-latest
    needs: deployment
    steps:
      - name: Checkout source code
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          fetch-depth: 0

      - name: Create branch and update to next SNAPSHOT version
        run: |
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git config --global user.name "${{ github.actor }}"
          git checkout -b ${{ env.SNAPSHOT_BRANCH_NAME }} master
          mvn versions:set versions:commit -DnextSnapshot
          git ls-files | grep 'pom.xml$' | xargs git add
          git commit --allow-empty -am "Update version to next SNAPSHOT"
          git push origin ${{ env.SNAPSHOT_BRANCH_NAME }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create PR for SNAPSHOT increment
        run: |
          gh pr create
                -B ${{ env.LATEST_BRANCH_NAME }}
                -H ${{ env.SNAPSHOT_BRANCH_NAME }}
                -t "Update to next SNAPSHOT version"
                -b "Update to next SNAPSHOT version"
        env:
            GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Enable Auto Merge on that PR
        run: |
          gh pr merge $(gh pr view --json number -q .number) --auto --merge
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}