name: Documentation Preview

on:
  pull_request:
    types:
      - opened
      - closed
      - synchronize
      - reopened
    paths:
      - mkdocs.yml                                        # static site generator config
      - .github/workflows/documentation-pr-preview.yml    # refers to this workflow file
      - docs/**                                           # actual documentation
      - sootup.examples/**                                # where example code that is included in the documentation is stored

concurrency:
  group: gh-pages

jobs:
  deploy-preview:
    name: Preview documentation
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write                               # for posting a comment

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Create Documentation Preview
        uses: secure-software-engineering/actions/documentation/pr-preview@develop