name: Deploy Documentation Version

permissions:
  pages: write
  deployments: write
  contents: write

on:
  push:
    branches:
      - master
      - develop

    paths:
      - 'mkdocs.yml'
      - 'sootup.examples/**'
      - 'docs/**'
      - 'documentation-version.yml'

concurrency: pages

jobs:
  deploy-snapshot:
    uses: secure-software-engineering/actions/pages/branch-snapshot-action.yml@develop
    with:
      latest_branch: develop
      version: "maven"