name: Documentation Deployment

on:
  push:
    branches:
      - develop
    tags:
      - '*'

concurrency:
  group: gh-pages

jobs:
  deploy-doc:
    name: Deploy Stable Documentation
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
          fetch-depth: 0              # mike needs full history to push to gh-pages

      - name: Generate Javadoc
        shell: bash
        run: mvn javadoc:javadoc      # generates javadoc in "target/site/apidocs"

      - name: Move generated Javadoc into docs directory
        shell: bash
        run: rm -rf docs/api; mkdir -p docs/api/; mv target/site/apidocs docs/api/

      - name: Download latest release of JimpleLSP jar - for use in Pygments+LspLexer4Pygments
        shell: bash
        run: curl -s -L -o ./jimplelsp.jar $(curl -s https://api.github.com/repos/swissiety/jimpleLsp/releases/latest | grep 'browser_download_url".*jar"' | cut -d ':' -f 2,3 | tr -d \")

      - name: Deploy Documentation
        uses: secure-software-engineering/actions/documentation/deployment@develop
        with:
          version: ${{ github.ref_name }}
