# see https://squidfunk.github.io/mkdocs-material/setup/setting-up-versioning/
# execute once, after the first deployment has 'latest' as alias:
# mike set-default latest --push

name: Documentation

on:
  push:
    branches:
      - master
      - develop
    paths:
      - 'mkdocs.yml'
      - 'sootup.examples/**'
      - 'docs/**'
      - '.github/workflows/gh-pages.yml'

  pull_request_target:
    types:
      - opened
      - reopened
      - synchronize
      - closed
    paths:
      - 'mkdocs.yml'
      - 'sootup.examples/**'
      - 'docs/**'
      - '.github/workflows/gh-pages.yml'

concurrency: pages

permissions:
  pages: write          # to trigger a gh-pages build
  deployments: write
  contents: write       # for creating files via mike/mkdocs
  pull-requests: write  # for commenting the link

jobs:
  manage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          fetch-tags: true      # to get tag information

      - uses: actions/setup-python@v2
        with:
          python-version: 3.x

      # install dependencies
      - run: pip install mike mkdocs-material mkdocs-tooltips git+https://github.com/RedisLabs/mkdocs-include.git git+https://github.com/swissiety/LspLexer4Pygments.git
      # grab latest release url of the JimpleLSP jar and download it
      - run: curl -s -L -o ./jimplelsp.jar $(curl -s https://api.github.com/repos/swissiety/jimpleLsp/releases/latest | grep 'browser_download_url".*jar"' | cut -d ':' -f 2,3 | tr -d \")

      - name: replace "{{ git_latest_release }}" with latest release tag version in .md files
        run: sed -i 's\{{ git_latest_release }}\'$(git tag --sort=committerdate | grep -E '[0-9]' | tail -1 | cut -b 2-7)'\g' docs/**.md

      - run: git fetch origin gh-pages --depth=1
      - name: Configure git user
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"

      # sanitize head_ref name
      - run: echo "DOC_VERSION_NAME=$(echo ${{ github.head_ref }} | sed "s/[^([[:alnum:]_.-]/_/g" )" >> $GITHUB_ENV

      # on PR events..
      - name: deploy doc in subdirectory
        if: startsWith(github.event_name, 'pull_request')
        run: mike deploy ${{ env.DOC_VERSION_NAME }}_preview -t "PR Preview ${{ env.DOC_VERSION_NAME }}" --push && mike props ${{ env.DOC_VERSION_NAME }}_preview --set-string hidden=true --push

      - name: comment link to preview
        if: startsWith(github.event_name, 'pull_request') && github.event.action != 'closed'
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          message: |
            [Documentation Preview](https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/${{ env.DOC_VERSION_NAME }}_preview/).

      # on PR close - delete preview
      - name: delete the deployed preview
        if: startsWith(github.event_name, 'pull_request') && github.event.action == 'closed'
        run: mike delete ${{ env.DOC_VERSION_NAME }}_preview --push

      # on push - documenatation to show the latest develop state
      - name: deploy doc in subdirectory
        if: github.event_name == 'push '&& github.base_ref == 'develop'
        run: mike deploy develop --push && mike deploy --push --update-aliases develop latest

      - name: deploy doc version for the new release
        if: github.event_name == 'push' && github.base_ref == 'master'
        # grab version from pom file
        run: mike deploy "$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout | sed "s/[^([[:alnum:]_.-]/_/g" )" --push