name: Check Formalities (Style, License, ... )

on:
  pull_request:
  merge_group:

permissions:
  contents: read
  pull-requests: read

jobs:
  check-formatting:
    # Reusable workflow: secure-software-engineering/actions/.github/workflows/maven-style-check.yml
    uses: secure-software-engineering/actions/.github/workflows/maven-style-check.yml@5df8d9ec2f3351fbb13f2a7782dcdc4502e1a4dc
    with:
      java_version: '17'
      java_distribution: adopt
