name: Check Formalities (Style, License, ... )

on:
  pull_request:
  merge_group:

permissions:
  contents: read

env:
  LATEST_BRANCH_NAME: develop
  FINAL_BRANCH_NAME: master

jobs:
  check-formatting:
    runs-on: ubuntu-latest
    name: Check style
    steps:
      - name: Checkout source code
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: Set up Java 17
        uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5.2.0
        with:
          distribution: adopt
          java-package: jdk
          java-version: 17

      - name: Check Format
        # Checks the formatting. Use "mvn com.spotify.fmt:fmt-maven-plugin:format" to format the code.
        run: mvn -B com.spotify.fmt:fmt-maven-plugin:check -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn

      - name: License Headers
        run: mvn -B org.codehaus.mojo:license-maven-plugin:check-file-header -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn

      - name: Check Javadoc
        run: mvn -B javadoc:aggregate -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn

      - name: Get Proposed Version
        run: |
          echo "PROPOSED_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_ENV

      - name: Check Semantic Versioning Pattern
        run: |
          echo "${{ env.PROPOSED_VERSION }}" | \
          grep -P '^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-((?:0|[1-9A-Za-z-][0-9A-Za-z-]*)(?:\.(?:0|[1-9A-Za-z-][0-9A-Za-z-]*))*))?(?:\+([0-9A-Za-z-]+(?:\.[0-9A-Za-z-]+)*))?$'

      - name: Enfore -SNAPSHOT version suffix on every other branch than master
        run: |
          HAS_SNAPSHOT_SUFFIX=$(echo "${{ env.PROPOSED_VERSION }}" | grep -q -- "-SNAPSHOT$")
          if [ "${{ github.base_ref == env.FINAL_BRANCH_NAME }}" ]; then
            if [ "$HAS_SNAPSHOT_SUFFIX" -eq 1 ]; then       # hint: command return values not boolean representation
              echo "To merge into ${{ github.base_ref }} a -SNAPSHOT suffix is allowed!"
              exit 1
            fi
          else
            if [ "$HAS_SNAPSHOT_SUFFIX" -eq 0 ]; then       # hint: command return values not boolean representation
              echo "To merge into ${{ github.base_ref }} a -SNAPSHOT suffix is needed!"
              exit 1
            fi
          fi

      - name: Ensure (strict) monotony of the version
        run: |
          TMP_POM=$(mktemp)
          HTTP_STATUS=$(curl -s -w "%{http_code}" \
                        -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
                        -H "Accept: application/vnd.github.v3.raw" \
                        -o "$TMP_POM" \
                        "https://api.github.com/repos/${{ github.repository }}/contents/pom.xml?ref=${{ github.base_ref }}")
          
          if [ "$HTTP_STATUS" -ne 200 ]; then
            echo "Warning: pom.xml not found in ${{ github.base_ref }}. HTTP status: $HTTP_STATUS."
            echo "Information: We assume the base branch is new and does not contain a pom.xml yet."
            rm "$TMP_POM"
            exit 0
          fi
          
          echo "Base branch pom.xml downloaded successfully."
          
          # hint: unfortunately mvn (as used above) fails if the downloaded pom is an aggregator pom and needs child poms as well
          LATEST_VERSION=$(grep -m1 '<version>' $TMP_POM | sed -E 's/.*<version>(.+)<\/version>.*/\1/')
          rm "$TMP_POM"

          # did the version not change? if not: master fails, other branches: ok      
          if [ "$LATEST_VERSION" == "${{ env.PROPOSED_VERSION }}" ]; then
            if [ "${{ github.base_ref }}" != "${{ env.FINAL_BRANCH_NAME }}" ]; then
              echo "No version change necessary on ${{ github.base_ref }}.";
              exit 0
            else
              echo "Version change necessary to merge into ${{ github.base_ref }}!";
              exit 1
            fi
          fi

          # is the new version higher? hint: does not handle 0.1.3-alpha versions.. just numbers! (or both with the same suffix like -SNAPHSOT)
          if [ "$(printf "%s\n%s" "${{ env.PROPOSED_VERSION }}" "$LATEST_VERSION" | sort -V | head -n1)" = "${{ env.PROPOSED_VERSION }}" ]; then
              echo "Proposed new version is lower than the latest version!"
              echo "${{ env.PROPOSED_VERSION }} <= $LATEST_VERSION"
              exit 1
          fi
