name: (Semantic) Versioning

on:
  pull_request:
    branches:
      - master
    types:
      - opened
      - reopened
      - synchronize

env:
  HEAD_BRANCH: develop

# cancel a running workflow if something new is pushed for the branch (to save calculation time budget)
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  # Code coverage (i.e. jacoco) needs the same classes for its test otherwise its classids can possibly not match
  Test:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0  # full history required

      - name: Set up JDK 17
        uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5.2.0
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: 'maven'

      - name: Determine Type of Version Increment
        # TODO: implement version update type mechanism
        run: |
          echo "VERSION_UPDATE_TYPE='minor')" >> GITHUB_ENV

      - name: Get latest Version from base branch
        run: |
          TMP_POM=$(mktemp)
          curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
                -H "Accept: application/vnd.github.v3.raw" \
                -O \
                https://api.github.com/repos/${{ github.repository }}/contents/pom.xml?ref=${{ github.base_ref }}
                -o "$TMP_POM"
          echo "LATEST_VERSION=$(mvn -f "$TMP_POM" org.apache.maven.plugins:maven-help-plugin:2.1.1:evaluate -Dexpression=project.version)" >> GITHUB_ENV
          rm "$TMP_POM"

      - name: calculate new version
        run: |
          if [[ "$semver" =~ ^([0-9]+)\.([0-9]+)\.([0-9]+)([-+].*)?$ ]]; then
            echo "latest_major=${BASH_REMATCH[1]}" >> GITHUB_ENV
            echo "latest_minor=${BASH_REMATCH[2]}" >> GITHUB_ENV
            echo "latest_patch=${BASH_REMATCH[3]}" >> GITHUB_ENV          
          fi

      - name: Calculate Major Version
        if: ${{ env.VERSION_UPDATE_TYPE == 'major' }}
        run: |
          echo "PROPOSED_VERSION=$(( ${{ env.latest_major }} +1 )).${{ env.latest_minor }}.${{ env.latest_patch }}" >> GITHUB_ENV

      - name: Calculate Minor Version
        if: ${{ env.VERSION_UPDATE_TYPE == 'minor' }}
        run: |          
          echo "PROPOSED_VERSION=${{ env.latest_major }}.$(( ${{ env.latest_minor }} + 1 )).${{ env.latest_patch }}" >> GITHUB_ENV

      - name: Bump Version
        run: |
          mvn build-helper:parse-version versions:set -DnewVersion='${{ env.PROPOSED_VERSION }}' versions:commit

      - name: Make version bump the last commit
        run: |
          VERSION_BUMP_COMMIT_MSG="${{ env.VERSION_UPDATE_TYPE }} bump ${{ env.PROPOSED_VERSION }} [version bump]"
          
          # Check if the last commit is the target message
          LAST_COMMIT_MSG=$(git log -1 --pretty=%B)
          
          if [[ "$LAST_COMMIT_MSG" != "$VERSION_BUMP_COMMIT_MSG" ]]; then
            # Version bump is not the last commit.

            # Fetch base branch
            git fetch origin ${{ github.base_ref }} 
  
            # Commit message tag for the version bump
            VERSION_TAG="[version bump]"
            
            # Get base commit (common ancestor)
            BASE=$(git merge-base HEAD origin/${{ github.base_ref }})
            
            # List commits unique to the PR
            COMMITS=$(git log --pretty=format:"%H|%s" ${BASE}..HEAD)
            
            FOUND_COMMIT=""
            for entry in $COMMITS; do
            
              # FIXME
              # MATCHING_COMMIT=$(git log --pretty=format:"%H %s" | grep -F "(major|minor|patch) $VERSION_BUMP_COMMIT_MSG" | tail -n 1 | awk '{print $1}')
              # if [[ -n "$MATCHING_COMMIT" ]]; then
            
              MSG=$(echo "$entry" | cut -d'|' -f2-)
              if [[ "$MSG" == *"$VERSION_TAG" ]]; then
                $MATCHING_COMMIT=$(echo "$entry" | cut -d'|' -f1)
                # Create rebase command to drop the commit
                echo "Delete version bump commit $MATCHING_COMMIT from ${{ github.ref_name }} ."
                git rebase -i --rebase-merges BASE) <<< "$(git log --pretty=oneline --abbrev-commit | \
                grep -v "$MATCHING_COMMIT" | \
                sed 's/^/pick /')"
            
                # commit and push version bump changes
                git ls-files | grep 'pom.xml$' | xargs git add
                git commit --allow-empty -am "$VERSION_BUMP_COMMIT_MSG"
                git push --force-with-lease
                
                exit 0;
              fi
            done
            
            echo "No version bump commit found in ${{ github.base_ref }} ."
          else
            echo "Version bump is already the last commit."
          fi